from stack_overflow_center.data_extractor.populators.tags_populator import TagsPopulator
from stack_overflow_center.data_extractor.populators.title_populator import TitlePopulator
from stack_overflow_center.data_extractor.populators.default_populator import DefaultPopulator
from stack_overflow_center.data_extractor.populators.question_body_populator import QuestionBodyPopulator

POPULATORS = [TagsPopulator, QuestionBodyPopulator, TitlePopulator, DefaultPopulator]
